query GetCycles {
  cycle {
    id
    startAt
    endAt
    remark
    predict_score
    title
    objectives {
      id
      title
      weight
      remark
      keyResults {
        id
        title
        unit
        total
        weight
        remark
        records {
          id
          remark
          quantity
          createdAt
        }
      }
    }
  }
}
